### ISSUE TITLE
convert-row like dataflye

### ISSUE THREAD

**Issue by rudolph-miller** [fukamachi/integral#15]
https://github.com/fukamachi/datafly/blob/e1c5a78759701e40d425e2101d9c5a105cba54a9/src/db.lisp#L81

**Comment by fukamachi** [comment]
What the function does in Integral since we have `select-dao`?

**Comment by rudolph-miller** [comment]
The point is [this](https://github.com/fukamachi/datafly/blob/e1c5a78759701e40d425e2101d9c5a105cba54a9/src/db.lisp#L71).
Now we `(retrieve-by-sql (select (:id :name) (from :user)))`, we get`((:|id| 1 :|name| "name1") (:|id| 2 :|name| "name2"))`.
