### ISSUE TITLE
How about inflate and deflate based on column-type

### ISSUE THREAD

**Issue by rudolph-miller** [fukamachi/integral#18]
like `(defmethod type-inflate ((type 'timestamp) value)
(local-time:universal-to-timestamp value))`

If Integral can handle type-inflate and type-deflate, people can handle custom type.

**Comment by rudolph-miller** [comment]
`(defclass user () ((name :type string) (tag :type cons)))`
`(defmethod deflate ((type cons) value) (list-to-csv value))`
`(defmethod inflate ((type cons) value) (csv-to-list value))`
or so.

**Comment by fukamachi** [comment]
Cool. I think it's quite useful :sparkles:
